### PR TITLE
Remove compression functionality

### PR DESCRIPTION
**Pull request by nxrighthere**
An additional cleanup to https://github.com/zpl-c/enet/commit/8c8cc837f24b76c816ed05f67228d988372fb865, and minor formatting changes.

### CODE REVIEW

**Comment by nxrighthere** [comment]
On hold/under consideration.

**Comment by zaklaus** [comment]
Is there a reason for its removal?

**Comment by zaklaus** [comment]
The thing is, isn't compression supposed to be considered as one of features that are irreplacable? Meaning, if we remove compression completely, can it be equally substituted from a higher level?

**Comment by nxrighthere** [comment]
Yea, this is done at a high-level in my networking layer. If I understand correctly, he wants to keep these callbacks to make compression possible at low-level for some reason.

**Comment by Croydon** [comment]
@nxrighthere I gave this pull request a thumbs down because I'm thinking that having compression directly in enet is a huge advantage. I didn't comment here since I assumed that it's clear what a thumbs down in a pull request which removes a feature means.

I noticed that you gave random issues I have opened in at least two completely different, unrelated projects a thumbs down for no apparently reason other than trolling.

I'm sorry if you did interpret my thumbs down as some kind of bulling or trolling, this was not my intention.

However, even if somebody is trolling you, you shouldn't go down the same path.

**Comment by nxrighthere** [comment]
> I'm thinking that having compression directly in enet is a huge advantage
No problem, show me where you use it in practice.

**Pull request closed without merging**
